#!/bin/bash

# Copyright 2020 Glen Reesor
#
# This file is part of gitsummary.
#
# Gitsummary is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Simple script to generate output that illustrates gitsummary
# features. To be used in conjunction with the file statuses
# as generated by the "example" scenario

COLOR_NORMAL='\033[0m'

COLOR_BRIGHT='\033[1m'
COLOR_AHEAD_BEHIND='\033[36m'

echo -e "                                   Remote     Target"
echo -e "  master                            .  ."
echo -e "  develop                           .  .      +5  .    master"
echo -e "  hotfix-stabilize-reactor-core     .  .      +2  .    master"
echo -e "${COLOR_BRIGHT}> feature-ds2-defences-phase2      ${COLOR_AHEAD_BEHIND}+3  .${COLOR_NORMAL}      +4  .    develop${COLOR_NORMAL}"
echo -e "  feature-endor-shield-generator    ${COLOR_AHEAD_BEHIND}.  -2${COLOR_NORMAL}     +5  -3   develop"

